from collections.abc import Callable

from funstruct.monad.option import Option

class Either[E, A]:
    """Either[E, A]: a value of type A, or an error of type E.

    Right-biased: bind/map/>> operate on A, short-circuit on E.
    When E = Exception, use the Result alias with Ok/Err vocabulary.
    """

    @classmethod
    def pure(cls, value: A) -> Either[E, A]: ...
    @classmethod
    def from_error(cls, error: E) -> Either[E, A]: ...
    def bind[B](self, f: Callable[[A], Either[E, B]]) -> Either[E, B]: ...
    def map[B](self, f: Callable[[A], B]) -> Either[E, B]: ...
    def ap[B](self, other: Either[E, B]) -> Either[E, tuple[A, B]]: ...
    def or_else[E2](self, f: Callable[[E], Either[E2, A]]) -> Either[E2, A]: ...
    def alt(self, f: Callable[[E], E]) -> Either[E, A]: ...
    def get_or_else(self, default: A) -> A: ...
    def fold[C](self, on_left: Callable[[E], C], on_right: Callable[[A], C]) -> C: ...
    def swap(self) -> Either[A, E]: ...
    def to_option(self) -> Option[A]: ...
    def map2[B, C](
        self, other: Either[E, B], f: Callable[[A, B], C]
    ) -> Either[E, C]: ...
    def flat_map[B](self, f: Callable[[A], Either[E, B]]) -> Either[E, B]: ...
    def __rshift__[B](self, f: Callable[[A], Either[E, B]]) -> Either[E, B]: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> Either: ...
    @classmethod
    def sequence(cls, eithers: object) -> Either: ...
    @classmethod
    def traverse(cls, values: object, f: Callable) -> Either: ...
    @property
    def is_right(self) -> bool: ...
    @property
    def is_left(self) -> bool: ...

class Right[E, A](Either[E, A]):
    """Success case. Aliased as Ok in the Result vocabulary."""

    value: A
    def __init__(self, value: A) -> None: ...

class Left[E, A](Either[E, A]):
    """Error case. Aliased as Err in the Result vocabulary."""

    error: E
    def __init__(self, error: E) -> None: ...
