from collections.abc import Awaitable, Callable, Generator

from funstruct.monad.either import Either

class Future[E, A]:
    def __init__(self, coro: Awaitable[Either[E, A]]) -> None: ...
    def __await__(self) -> Generator[None, None, Either[E, A]]: ...
    def map[B](self, f: Callable[[A], B]) -> Future[E, B]: ...
    def bind[B](self, f: Callable[[A], Future[E, B]]) -> Future[E, B]: ...
    def bind_either[B](self, f: Callable[[A], Either[E, B]]) -> Future[E, B]: ...
    def bind_awaitable[B](self, f: Callable[[A], Awaitable[B]]) -> Future[E, B]: ...
    def alt(self, f: Callable[[E], E]) -> Future[E, A]: ...
    def or_else(self, f: Callable[[E], Future[E, A]]) -> Future[E, A]: ...
    def or_else_either(self, f: Callable[[E], Either[E, A]]) -> Future[E, A]: ...
    def then[B](self, next_future: Future[E, B]) -> Future[E, B]: ...
    def ap[B](self, other: Future[E, B]) -> Future[E, tuple[A, B]]: ...
    @classmethod
    def pure(cls, value: A) -> Future[E, A]: ...
    @classmethod
    def from_error(cls, error: E) -> Future[E, A]: ...
    @classmethod
    def from_either(cls, either: Either[E, A]) -> Future[E, A]: ...
    @classmethod
    def from_coroutine(cls, coro: Awaitable[A]) -> Future[Exception, A]: ...
