from collections.abc import Callable

from funstruct.monad.either import Either

class Option[A]:
    @classmethod
    def pure(cls, value: A) -> Option[A]: ...
    @classmethod
    def from_optional(cls, value: A | None) -> Option[A]: ...
    def bind[B](self, f: Callable[[A], Option[B]]) -> Option[B]: ...
    def map[B](self, f: Callable[[A], B]) -> Option[B]: ...
    def ap[B](self, other: Option[B]) -> Option[tuple[A, B]]: ...
    def get_or_else(self, default: A) -> A: ...
    def or_else(self, fallback: Callable[[], Option[A]]) -> Option[A]: ...
    def filter(self, f: Callable[[A], bool]) -> Option[A]: ...
    def fold[C](self, on_nothing: Callable[[], C], on_some: Callable[[A], C]) -> C: ...
    def to_result[E](self, error: E) -> Either[E, A]: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> Option: ...
    @classmethod
    def sequence(cls, options: object) -> Option: ...
    @classmethod
    def traverse(cls, values: object, f: Callable) -> Option: ...
    @property
    def is_some(self) -> bool: ...
    @property
    def is_nothing(self) -> bool: ...

class Some[A](Option[A]):
    value: A
    def __init__(self, value: A) -> None: ...
    def __bool__(self) -> bool: ...

class Nothing(Option):
    def __bool__(self) -> bool: ...
