from collections.abc import Callable

class Reader[Ctx, A]:
    def __init__(self, run: Callable[[Ctx], A]) -> None: ...
    def run(self, ctx: Ctx) -> A: ...
    def bind[B](self, f: Callable[[A], Reader[Ctx, B]]) -> Reader[Ctx, B]: ...
    def map[B](self, f: Callable[[A], B]) -> Reader[Ctx, B]: ...
    def __rshift__[B](self, f: Callable[[A], Reader[Ctx, B]]) -> Reader[Ctx, B]: ...
    @classmethod
    def pure(cls, value: A) -> Reader[Ctx, A]: ...
    @classmethod
    def ask(cls) -> Reader[Ctx, Ctx]: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> Reader: ...
