from collections.abc import Callable

class State[S, A]:
    def __init__(self, run: Callable[[S], tuple[S, A]]) -> None: ...
    def run(self, initial_state: S) -> tuple[S, A]: ...
    def bind[B](self, f: Callable[[A], State[S, B]]) -> State[S, B]: ...
    def map[B](self, f: Callable[[A], B]) -> State[S, B]: ...
    def then[B](self, next_state: State[S, B]) -> State[S, B]: ...
    def __rshift__[B](self, f: Callable[[A], State[S, B]]) -> State[S, B]: ...
    @classmethod
    def pure(cls, value: A) -> State[S, A]: ...
    @classmethod
    def get(cls) -> State[S, S]: ...
    @classmethod
    def modify(cls, f: Callable[[S], S]) -> State[S, None]: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> State: ...
