from collections.abc import Callable
from typing import Any

from funstruct.typeclasses import Monoid

class Writer[W, A]:
    _monoid: Monoid
    value: A
    output: W
    def __init__(self, value: A, output: W) -> None: ...
    def bind[B](self, f: Callable[[A], Writer[W, B]]) -> Writer[W, B]: ...
    def map[B](self, f: Callable[[A], B]) -> Writer[W, B]: ...
    def __rshift__[B](self, f: Callable[[A], Writer[W, B]]) -> Writer[W, B]: ...
    @classmethod
    def pure(cls, value: A) -> Writer[W, A]: ...
    @classmethod
    def tell(cls, output: W) -> Writer[W, None]: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> Writer: ...

class ListWriter(Writer[list[Any], Any]): ...
class CListWriter(Writer[Any, Any]): ...
class StrWriter(Writer[str, Any]): ...
class IntWriter(Writer[int, Any]): ...
