repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v4.0.0-alpha.8
    hooks:
      - id: ruff-format  # Run the formatter.
        args:
          - --config
          - pyproject.toml
      - id: ruff  # Run the linter.
        args:
          - --config
          - pyproject.toml
          - --fix
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        files: ^\.github/workflows/
      - id: prettier
        types: [markdown]
        args: [--prose-wrap, always, --print-width, "88"]
  - id: typecheck
    name: typecheck
    entry: bash -c "just check"
    language: system
    pass_filenames: false
