default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-format # Run the formatter.
        args:
          - --config
          - pyproject.toml
      - id: ruff # Run the linter.
        args:
          - --config
          - pyproject.toml
          - --fix
        stages: [pre-push]
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-mkdocs
  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        entry: bash -c "just check"
        language: system
        pass_filenames: false
        stages: [pre-push]
