from funstruct.monad.either import Either
from funstruct.monad.option import Option

def option_to_result[A, E](opt: Option[A], error: E) -> Either[E, A]: ...
def result_to_option[A](result: Either) -> Option[A]: ...
