from collections.abc import Callable

from funstruct.monad.either import Either
from funstruct.monad.option import Option

class ReaderT[F, Ctx, A]:
    def __init__(self, run: Callable[[Ctx], F]) -> None: ...
    def run(self, ctx: Ctx) -> F: ...
    def __call__(self, ctx: Ctx) -> F: ...
    def bind[B](self, f: Callable[[A], ReaderT[F, Ctx, B]]) -> ReaderT[F, Ctx, B]: ...
    def map[B](self, f: Callable[[A], B]) -> ReaderT[F, Ctx, B]: ...
    def or_else(self, f: Callable) -> ReaderT[F, Ctx, A]: ...
    def and_then(self, other: ReaderT) -> ReaderT: ...
    def then[B](self, next_step: ReaderT[F, Ctx, B]) -> ReaderT[F, Ctx, B]: ...
    @classmethod
    def pure(cls, value: A, monad: type) -> ReaderT: ...
    @classmethod
    def lift(cls, m: F) -> ReaderT: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> ReaderT: ...

class StateT[F, S, A]:
    def __init__(self, run: Callable[[S], F]) -> None: ...
    def run(self, initial_state: S) -> F: ...
    def bind[B](self, f: Callable[[A], StateT[F, S, B]]) -> StateT[F, S, B]: ...
    def map[B](self, f: Callable[[A], B]) -> StateT[F, S, B]: ...
    def or_else(self, f: Callable) -> StateT: ...
    def and_then(self, other: StateT) -> StateT: ...
    def then[B](self, next_state: StateT[F, S, B]) -> StateT[F, S, B]: ...
    @classmethod
    def pure(cls, value: A, monad: type) -> StateT: ...
    @classmethod
    def fail(cls, err: object, monad: type) -> StateT: ...
    @classmethod
    def get(cls, monad: type) -> StateT: ...
    @classmethod
    def modify(cls, f: Callable, monad: type) -> StateT: ...
    @classmethod
    def lift(cls, inner: object) -> StateT: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> StateT: ...

class EitherT[F, E, A]:
    def __init__(self, run: F) -> None: ...
    def run(self) -> F: ...
    def bind[B](self, f: Callable[[A], EitherT[F, E, B]]) -> EitherT[F, E, B]: ...
    def map[B](self, f: Callable[[A], B]) -> EitherT[F, E, B]: ...
    def or_else(self, f: Callable) -> EitherT: ...
    def then[B](self, other: EitherT[F, E, B]) -> EitherT[F, E, B]: ...
    @classmethod
    def pure(cls, value: A, monad: type) -> EitherT: ...
    @classmethod
    def from_error(cls, error: E, monad: type) -> EitherT: ...
    @classmethod
    def from_either(cls, either: Either[E, A], monad: type) -> EitherT: ...
    @classmethod
    def lift(cls, fa: F) -> EitherT: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> EitherT: ...

class OptionT[F, A]:
    def __init__(self, run: F) -> None: ...
    def run(self) -> F: ...
    def bind[B](self, f: Callable[[A], OptionT[F, B]]) -> OptionT[F, B]: ...
    def map[B](self, f: Callable[[A], B]) -> OptionT[F, B]: ...
    def or_else(self, f: Callable) -> OptionT: ...
    def then[B](self, other: OptionT[F, B]) -> OptionT[F, B]: ...
    @classmethod
    def pure(cls, value: A, monad: type) -> OptionT: ...
    @classmethod
    def none(cls, monad: type) -> OptionT: ...
    @classmethod
    def lift(cls, fa: F) -> OptionT: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> OptionT: ...

class WriterT[F, W, A]:
    def __init__(self, run: F) -> None: ...
    def run(self) -> F: ...
    def bind[B](self, f: Callable[[A], WriterT[F, W, B]]) -> WriterT[F, W, B]: ...
    def map[B](self, f: Callable[[A], B]) -> WriterT[F, W, B]: ...
    def then[B](self, other: WriterT[F, W, B]) -> WriterT[F, W, B]: ...
    @classmethod
    def pure(cls, value: A, monad: type) -> WriterT: ...
    @classmethod
    def tell(cls, output: W, monad: type) -> WriterT: ...
    @classmethod
    def lift(cls, fa: F) -> WriterT: ...
    @classmethod
    def do(cls, gen_fn: Callable) -> WriterT: ...
