from collections.abc import Callable
from typing import Any

from funstruct.monad.either import Either

class Validated:
    @staticmethod
    def valid[A](value: A) -> Valid[A]: ...
    @staticmethod
    def invalid[E](error: E) -> Invalid[list[E]]: ...
    @staticmethod
    def cond[A, E](test: bool, value: A, error: E) -> Valid[A] | Invalid[list[E]]: ...

class Valid[A](Validated):
    value: A
    def __init__(self, value: A) -> None: ...
    def map[B](self, f: Callable[[A], B]) -> Valid[B]: ...
    def ap[B](self, other: Validated) -> Validated: ...
    def fold[C](self, on_invalid: Callable, on_valid: Callable[[A], C]) -> C: ...
    def to_result(self) -> Either[Exception, A]: ...
    def to_result_or(self, exc_cls: type[Exception]) -> Either[Exception, A]: ...
    @property
    def is_valid(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __add__(self, other: Validated) -> Validated: ...

class Invalid[E](Validated):
    errors: E
    def __init__(self, errors: E) -> None: ...
    def map(self, f: Callable) -> Invalid[E]: ...
    def ap(self, other: Validated) -> Invalid: ...
    def fold[C](self, on_invalid: Callable[[E], C], on_valid: Callable) -> C: ...
    def to_result(self) -> Either[Exception, Any]: ...
    def to_result_or(
        self, exc_cls: type[Exception], combine: Callable = ...
    ) -> Either[Exception, Any]: ...
    @property
    def is_valid(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __add__(self, other: Validated) -> Invalid: ...
