from collections.abc import Callable, Iterable, Iterator

class CList[A]:
    def map[B](self, f: Callable[[A], B]) -> CList[B]: ...
    def bind[B](self, f: Callable[[A], CList[B]]) -> CList[B]: ...
    def flat_map[B](self, f: Callable[[A], CList[B]]) -> CList[B]: ...
    def filter(self, f: Callable[[A], bool]) -> CList[A]: ...
    def fold_left[B](self, acc: B, f: Callable[[B, A], B]) -> B: ...
    def fold_right[B](self, acc: B, f: Callable[[A, B], B]) -> B: ...
    def append(self, other: CList[A]) -> CList[A]: ...
    def reversed(self) -> CList[A]: ...
    def prepend(self, new_head: A) -> CList[A]: ...
    def drop(self, n: int) -> CList[A]: ...
    def drop_while(self, f: Callable[[A], bool]) -> CList[A]: ...
    def take(self, n: int) -> CList[A]: ...
    def take_while(self, f: Callable[[A], bool]) -> CList[A]: ...
    def split_at(self, i: int) -> tuple[CList[A], CList[A]]: ...
    def insert_at(self, i: int, value: A) -> CList[A]: ...
    def to_list(self) -> list[A]: ...
    def ap[B](self, other: CList[B]) -> CList[tuple[A, B]]: ...
    def __iter__(self) -> Iterator[A]: ...
    def __len__(self) -> int: ...
    def __add__(self, other: CList[A]) -> CList[A]: ...
    def __eq__(self, other: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def __rlshift__(self, other: A) -> CList[A]: ...
    @classmethod
    def pure(cls, value: A) -> CList[A]: ...
    @staticmethod
    def new(*xs: A) -> CList[A]: ...
    @staticmethod
    def from_iterable(iterable: Iterable[A]) -> CList[A]: ...

class Nil(CList):
    def __bool__(self) -> bool: ...

class Cons[A](CList[A]):
    head: A
    tail: CList[A]
    def __init__(self, head: A, tail: CList[A] = ...) -> None: ...
    def __bool__(self) -> bool: ...
