from collections.abc import Callable, ItemsView, Iterator, KeysView, ValuesView

class frozendict[K, V]:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def get(self, key: K) -> V | None: ...
    def put(self, k: K, v: V) -> frozendict[K, V]: ...
    def remove(self, k: K) -> frozendict[K, V]: ...
    def combine(self, other: frozendict[K, V]) -> frozendict[K, V]: ...
    def map[V2](self, f: Callable[[V], V2]) -> frozendict[K, V2]: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> ValuesView[V]: ...
    def items(self) -> ItemsView[K, V]: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: K) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __add__(self, other: frozendict[K, V]) -> frozendict[K, V]: ...
    def __bool__(self) -> bool: ...
    @property
    def raw(self) -> dict[K, V]: ...
    @staticmethod
    def new() -> frozendict: ...
    @classmethod
    def fromkeys(cls, *args: object, **kwargs: object) -> frozendict: ...
